wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.27.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683938212.391985
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 23
      4: 3.10.11
      5: 0.15.2
      6: 4.27.1
      8:
      - 5
